import { prisma } from '@/lib/db/prisma';
import type { PMPlan, CTOArchitecture } from '@/types';
import fs from 'fs/promises';
import path from 'path';

const PROJECTS_ROOT = 'C:/tpml-ai-team/projects';

interface ProjectWithPlan {
  id: string;
  name: string;
  slug: string;
  pmPlan: unknown;
  ctoArchitecture: unknown;
  intakeData: unknown;
}

export async function generateArtifacts(project: ProjectWithPlan) {
  const pmPlan = project.pmPlan as PMPlan;
  const ctoArchitecture = project.ctoArchitecture as CTOArchitecture;
  const intake = project.intakeData as { client?: string; problemStatement?: string };

  // Generate BACKLOG.md
  const backlogContent = generateBacklogMarkdown(project.name, intake.client || 'Unknown', pmPlan);

  // Generate ARCHITECTURE.md
  const architectureContent = generateArchitectureMarkdown(project.name, ctoArchitecture);

  // Store artifacts in database
  await prisma.artifact.createMany({
    data: [
      {
        projectId: project.id,
        type: 'BACKLOG',
        name: 'BACKLOG.md',
        content: backlogContent,
        version: 1,
      },
      {
        projectId: project.id,
        type: 'ARCHITECTURE',
        name: 'ARCHITECTURE.md',
        content: architectureContent,
        version: 1,
      },
    ],
  });

  // Write artifacts to project folder
  try {
    const docsPath = path.join(PROJECTS_ROOT, project.slug, 'docs');
    await fs.mkdir(docsPath, { recursive: true });
    await fs.writeFile(path.join(docsPath, 'BACKLOG.md'), backlogContent);
    await fs.writeFile(path.join(docsPath, 'ARCHITECTURE.md'), architectureContent);
    console.log(`[Artifacts] Written to ${docsPath}`);
  } catch (err) {
    console.warn('[Artifacts] Failed to write to project folder:', err);
    // Don't fail if folder write fails - database is primary
  }

  // Create sprints from PM plan
  for (const sprint of pmPlan.sprints) {
    await prisma.sprint.create({
      data: {
        projectId: project.id,
        number: sprint.number,
        name: sprint.name,
        goal: sprint.goal,
        status: 'PLANNED',
      },
    });
  }

  return { backlogContent, architectureContent };
}

function generateBacklogMarkdown(projectName: string, client: string, pmPlan: PMPlan): string {
  const today = new Date().toISOString().split('T')[0];

  let content = `# ${projectName} — Product Backlog

## Metadata

- **Project:** ${projectName}
- **Client:** ${client}
- **Generated:** ${today}
- **Status:** Planning Complete

---

## MVP Definition

${pmPlan.mvp.description}

### Key Features

${pmPlan.mvp.features.map(f => `- ${f}`).join('\n')}

---

## Sprint Plan

`;

  for (const sprint of pmPlan.sprints) {
    content += `### Sprint ${sprint.number}: ${sprint.name}
**Duration:** ${sprint.duration}
**Goal:** ${sprint.goal}

| ID | Feature | Priority | Acceptance Criteria |
|----|---------|----------|---------------------|
`;

    const sprintBacklog = pmPlan.backlog.filter(b => b.sprint === sprint.number);
    for (const item of sprintBacklog) {
      const criteria = item.acceptanceCriteria.join('; ');
      content += `| ${item.id} | ${item.feature} | ${item.priority} | ${criteria} |\n`;
    }

    content += '\n---\n\n';
  }

  content += `## Timeline

${pmPlan.timeline}

---

## Risks

${pmPlan.risks.map(r => `- ${r}`).join('\n')}

---

*Generated by TPML Operations Dashboard*
`;

  return content;
}

function generateArchitectureMarkdown(projectName: string, cto: CTOArchitecture): string {
  const today = new Date().toISOString().split('T')[0];

  let content = `# ${projectName} — Technical Architecture

## Metadata

- **Project:** ${projectName}
- **Generated:** ${today}
- **Author:** AI CTO

---

## Tech Stack

| Component | Technology | Notes |
|-----------|------------|-------|
| Framework | ${cto.techStack.framework} | |
| Database | ${cto.techStack.database} | |
| Auth | ${cto.techStack.auth} | |
| Hosting | ${cto.techStack.hosting} | |

${cto.techStack.notes ? `**Notes:** ${cto.techStack.notes}` : ''}

---

## Data Model

`;

  for (const entity of cto.dataModel.entities) {
    content += `### ${entity.name}

**Fields:**
${entity.fields.map(f => `- ${f}`).join('\n')}

**Relations:**
${entity.relations.map(r => `- ${r}`).join('\n')}

`;
  }

  content += `---

## API Routes

| Method | Path | Description |
|--------|------|-------------|
`;

  for (const route of cto.apiRoutes) {
    content += `| ${route.method} | ${route.path} | ${route.description} |\n`;
  }

  content += `
---

## Integrations

${cto.integrations.map(i => `- ${i}`).join('\n')}

---

## Technical Risks

${cto.technicalRisks.map(r => `- ${r}`).join('\n')}

---

*Generated by TPML Operations Dashboard*
`;

  return content;
}
